name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11-alpine
        env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
