  name: intergration

  on:
    push:
      branches: [master]

    pull_request:
      branches: [master]

  jobs:
    build:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:12.1-alpine

  steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Set up Ruby 3.0
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 3.0
        - run: bundle exec rake
        - name: Setup cache key and directory for gems cache
          uses: actions/cache@v1
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
